global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'fastapi'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: [ 'fast_api:8000' ]

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: telegraf
    scrape_interval: 15s
    static_configs:
      - targets: [ 'telegraf:9100' ]
