"""add column

Revision ID: 4cf611186aa5
Revises: 37b3f77890ed
Create Date: 2023-09-08 06:58:12.033858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cf611186aa5'
down_revision: Union[str, None] = '37b3f77890ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_statistic', sa.Column('chat_model', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_statistic', 'chat_model')
    # ### end Alembic commands ###
